In [12]:
import os
import pandas as pd

data_dir = "D:/SurfaceRecognitionModel/data"  # update based on your system
csv_files = [f for f in os.listdir(data_dir) if f.endswith('.csv')]

for file in csv_files:
    file_path = os.path.join(data_dir, file)
    try:
        df = pd.read_csv(file_path)
        print(f"\n📂 File: {file} — First 10 rows:")
        print(df.head(10))
        input("🔘 Press Enter to continue...")
    except Exception as e:
        print(f"❌ Error reading {file}: {e}")



📂 File: ACRYLIC_1.csv — First 10 rows:
   Time  Resistance
0     1     7254.73
1     2     7893.90
2     3     8091.35
3     4     8130.83
4     5     7933.59
5     6     7961.72
6     7     8358.54
7     8     8730.94
8     9     8557.11
9    10    10247.37


🔘 Press Enter to continue... 



📂 File: BUBBLEWRAP BACK_1.csv — First 10 rows:
   Time  Resistance
0     1     6847.83
1     2     6686.18
2     3     6549.35
3     4     7614.00
4     5     9372.12
5     6     9121.49
6     7    10036.41
7     8     8791.25
8     9     8560.50
9    10     8874.89


🔘 Press Enter to continue... 



📂 File: BUBBLEWRAP FRONT_1.csv — First 10 rows:
   Time  Resistance  Unnamed: 2  Unnamed: 3  Unnamed: 4 Unnamed: 5
0     1     7055.57         NaN         NaN         NaN        NaN
1     2     6979.49         NaN         NaN         NaN        NaN
2     3     7127.05         NaN         NaN         NaN        NaN
3     4     7423.59         NaN         NaN         NaN        NaN
4     5     7858.91         NaN         NaN         NaN        NaN
5     6     9245.95         NaN         NaN         NaN        NaN
6     7     9482.47         NaN         NaN         NaN        NaN
7     8     9367.53         NaN         NaN         NaN          ?
8     9     8369.98         NaN         NaN         NaN        NaN
9    10     9483.76         NaN         NaN         NaN        NaN


🔘 Press Enter to continue... 



📂 File: CARDBOARD_1.csv — First 10 rows:
    1   5271.06  Unnamed: 2  Unnamed: 3 Unnamed: 4
0   2   5346.55         NaN         NaN        NaN
1   3   5501.80         NaN         NaN        NaN
2   4   5531.54         NaN         NaN        NaN
3   5   5545.04         NaN         NaN        NaN
4   6   6592.86         NaN         NaN        NaN
5   7   7895.55         NaN         NaN        NaN
6   8   8019.89         NaN         NaN          ?
7   9   9077.12         NaN         NaN        NaN
8  10   8045.05         NaN         NaN        NaN
9  11  11497.94         NaN         NaN        NaN


🔘 Press Enter to continue... 



📂 File: GLASS_1.csv — First 10 rows:
   Time  Resistance
0     1     7208.84
1     2     7259.89
2     3    11563.53
3     4    13599.23
4     5    13553.84
5     6    14325.82
6     7    15641.78
7     8    11884.10
8     9    17777.72
9    10    15003.44


🔘 Press Enter to continue... 



📂 File: GLOVE_1.csv — First 10 rows:
   Time  Resistance  Unnamed: 2  Unnamed: 3 Unnamed: 4
0     1     7782.02         NaN         NaN        NaN
1     2     7628.49         NaN         NaN        NaN
2     3     7524.28         NaN         NaN        NaN
3     4     7183.81         NaN         NaN        NaN
4     5     7720.31         NaN         NaN        NaN
5     6     9138.75         NaN         NaN        NaN
6     7     8881.72         NaN         NaN        NaN
7     8     9897.66         NaN         NaN          ?
8     9     8701.35         NaN         NaN        NaN
9    10    14879.96         NaN         NaN        NaN


🔘 Press Enter to continue... 



📂 File: MARBLE_1.csv — First 10 rows:
   Time  Resistance
0     1     6820.29
1     2     5895.30
2     3     5896.01
3     4     8067.55
4     5   209707.92
5     6    13854.78
6     7     4522.74
7     8     3087.20
8     9    14389.56
9    10     4609.92


🔘 Press Enter to continue... 



📂 File: METAL_1.csv — First 10 rows:
   Time  Resistance
0     1     4967.72
1     2     4964.07
2     3     4917.59
3     4     4881.40
4     5     4909.83
5     6     5283.04
6     7     6088.49
7     8     5869.14
8     9     6261.73
9    10     7327.21


🔘 Press Enter to continue... 



📂 File: PAPER_1.csv — First 10 rows:
   Time  Resistance
0     1     8824.68
1     2    13266.33
2     3    16550.91
3     4    16923.30
4     5    20989.39
5     6    17369.66
6     7     7754.21
7     8    10820.73
8     9    13169.10
9    10    18509.35


🔘 Press Enter to continue... 



📂 File: SMOOTH WOODEN_1.csv — First 10 rows:
   Time  Resistance
0     1     6293.07
1     2     6246.57
2     3     6338.27
3     4     6673.42
4     5     6489.70
5     6     9311.93
6     7     8121.70
7     8    18523.31
8     9    14516.83
9    10     6838.91


🔘 Press Enter to continue... 


In [13]:
import os
import pandas as pd
import numpy as np

folder_path = "D:/SurfaceRecognitionModel/data"  # change if needed
csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]

cleaned_dfs = []

for file in csv_files:
    try:
        file_path = os.path.join(folder_path, file)
        df = pd.read_csv(file_path)

        # Replace '?' with NaN and drop all-NaN columns
        df.replace("?", np.nan, inplace=True)
        df.dropna(axis=1, how='all', inplace=True)

        # Drop columns like 'Unnamed'
        df = df.loc[:, ~df.columns.str.contains("^Unnamed", na=False)]

        # Keep only numeric columns
        df = df.select_dtypes(include=[np.number])

        # Add default Time column if needed
        if df.shape[1] == 1:
            df.insert(0, "Time", range(1, len(df)+1))

        # Standardize column names
        df.columns = ['Time', 'Resistance'] + list(df.columns[2:])

        # Add surface label from filename
        surface_label = file.replace(".csv", "").split("_")[0].upper()
        df["Surface"] = surface_label

        cleaned_dfs.append(df)

    except Exception as e:
        print(f"❌ Error in {file}: {e}")

# Combine all into a master clean dataset
if cleaned_dfs:
    combined_df = pd.concat(cleaned_dfs, ignore_index=True)
    combined_df.to_csv(os.path.join(folder_path, "Cleaned_Surface_Data.csv"), index=False)
    print("✅ Cleaning completed! File saved as 'Cleaned_Surface_Data.csv'")
    print(combined_df.head())

else:
    print("❌ No valid CSVs were processed.")


✅ Cleaning completed! File saved as 'Cleaned_Surface_Data.csv'
   Time  Resistance  Surface
0     1     7254.73  ACRYLIC
1     2     7893.90  ACRYLIC
2     3     8091.35  ACRYLIC
3     4     8130.83  ACRYLIC
4     5     7933.59  ACRYLIC


C:\Users\ASUS\AppData\Local\Temp\ipykernel_10328\2894335364.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("?", np.nan, inplace=True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_10328\2894335364.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace("?", np.nan, inplace=True)
C:\Users\ASUS\AppData\Local\Temp\ipykernel_10328\2894335364.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objec

In [14]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Load the cleaned data
df = pd.read_csv("D:/SurfaceRecognitionModel/data/Cleaned_Surface_Data.csv")

# Prepare features and labels
X = df[['Resistance']]  # Only Resistance as input
y = df['Surface']       # Surface label as target

# Encode surface labels
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# Train Random Forest
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

# Predict and evaluate
y_pred = clf.predict(X_test)

print("📊 Classification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))
print("📉 Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


📊 Classification Report:
                  precision    recall  f1-score   support

         ACRYLIC       0.12      0.10      0.11        30
 BUBBLEWRAP BACK       0.23      0.23      0.23        53
BUBBLEWRAP FRONT       0.16      0.11      0.13        38
       CARDBOARD       0.31      0.32      0.32        37
           GLASS       0.12      0.16      0.14        25
           GLOVE       0.18      0.13      0.15        30
          MARBLE       0.58      0.67      0.62        39
           METAL       0.26      0.25      0.25        32
           PAPER       0.29      0.44      0.35        16
   SMOOTH WOODEN       0.22      0.24      0.23        38

        accuracy                           0.26       338
       macro avg       0.25      0.26      0.25       338
    weighted avg       0.25      0.26      0.26       338

📉 Confusion Matrix:
[[ 3  5  1  2  4  5  1  3  1  5]
 [ 5 12  6  5  4  4  3  5  1  8]
 [ 0 11  4  4  0  1 11  3  0  4]
 [ 5  5  2 12  3  1  2  5  1  1]
 [ 2  2 

In [16]:
!pip install xgboost

   ---------------------------------------- 0.0/150.0 MB ? eta -:--:--
   ---------------------------------------- 1.8/150.0 MB 10.1 MB/s eta 0:00:15
    --------------------------------------- 3.7/150.0 MB 9.5 MB/s eta 0:00:16
   - -------------------------------------- 5.8/150.0 MB 9.8 MB/s eta 0:00:15
   -- ------------------------------------- 8.1/150.0 MB 10.1 MB/s eta 0:00:15
   -- ------------------------------------- 10.5/150.0 MB 10.2 MB/s eta 0:00:14
   --- ------------------------------------ 12.8/150.0 MB 10.3 MB/s eta 0:00:14
   ---- ----------------------------------- 15.5/150.0 MB 10.6 MB/s eta 0:00:13
   ---- ----------------------------------- 17.6/150.0 MB 10.5 MB/s eta 0:00:13
   ----- ---------------------------------- 19.9/150.0 MB 10.6 MB/s eta 0:00:13
   ------ --------------------------------- 22.5/150.0 MB 10.7 MB/s eta 0:00:12
   ------ --------------------------------- 24.6/150.0 MB 10.8 MB/s eta 0:00:12
   ------- -------------------------------- 27.0/150.0 

In [19]:
!pip install imbalanced-learn

In [20]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

# 1️⃣ Load Cleaned Data
df = pd.read_csv("D:/SurfaceRecognitionModel/data/Cleaned_Surface_Data.csv")

# 2️⃣ Remove outliers (very high resistance)
df = df[df['Resistance'] < 50000]

# 3️⃣ Feature Engineering
df['Resistance_diff'] = df['Resistance'].diff().fillna(0)
df['Rolling_mean_5'] = df['Resistance'].rolling(5).mean().fillna(method='bfill')
df['Rolling_std_5'] = df['Resistance'].rolling(5).std().fillna(method='bfill')

# 4️⃣ Prepare Features & Labels
X = df[['Resistance', 'Resistance_diff', 'Rolling_mean_5', 'Rolling_std_5']]
y = df['Surface']
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# 5️⃣ Balance Dataset with SMOTE
X_resampled, y_resampled = SMOTE(random_state=42).fit_resample(X, y_encoded)

# 6️⃣ Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

# 7️⃣ Train XGBoost Classifier
model = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss', random_state=42)
model.fit(X_train, y_train)

# 8️⃣ Evaluate
y_pred = model.predict(X_test)

print("✅ Classification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))
print("📉 Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


C:\Users\ASUS\AppData\Local\Temp\ipykernel_10328\1252594953.py:17: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Rolling_mean_5'] = df['Resistance'].rolling(5).mean().fillna(method='bfill')
C:\Users\ASUS\AppData\Local\Temp\ipykernel_10328\1252594953.py:18: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Rolling_std_5'] = df['Resistance'].rolling(5).std().fillna(method='bfill')
D:\SurfaceRecognitionModel\surface\Lib\site-packages\xgboost\training.py:183: UserWarning: [00:42:06] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


✅ Classification Report:
                  precision    recall  f1-score   support

         ACRYLIC       0.53      0.65      0.59        37
 BUBBLEWRAP BACK       0.51      0.40      0.45        52
BUBBLEWRAP FRONT       0.82      0.80      0.81        69
       CARDBOARD       0.65      0.69      0.67        45
           GLASS       0.68      0.75      0.71        48
           GLOVE       0.60      0.66      0.62        38
          MARBLE       0.84      0.85      0.85        48
           METAL       0.64      0.67      0.65        52
           PAPER       0.75      0.80      0.77        54
   SMOOTH WOODEN       0.77      0.57      0.65        53

        accuracy                           0.69       496
       macro avg       0.68      0.68      0.68       496
    weighted avg       0.69      0.69      0.69       496

📉 Confusion Matrix:
[[24  4  0  2  0  3  0  0  0  4]
 [ 5 21  3  8  3  5  0  4  3  0]
 [ 0  1 55  1  0  2  5  5  0  0]
 [ 2  4  2 31  0  0  0  5  0  1]
 [ 1  1 

In [23]:
!pip install optuna


  Using cached colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
  Using cached tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------- ----- 1.8/2.1 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 7.9 MB/s eta 0:00:00
Using cached colorlog-6.9.0-py3-none-any.whl (11 kB)
Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)

  Attempting uninstall: typing-extensions

    Found existing installation: typing_extensions 4.9.0

    Uninstalling typing_extensions-4.9.0:

   ---------------------------------------- 0/8 [typing-extensions]
   ---------------------------------------- 0/8 [typing-extensions]
   ---------------------------------------- 0/8 [typing-extensions]
   ---------------------------------------- 0/8 [typing-extensions]
   ---------------------------------------- 0/8 [typing-extensions]
   ---------------------------------------- 0/8 [typing-extensions

In [24]:
df['Slope'] = df['Resistance'].diff().fillna(0)  # Rate of change
df['EMA'] = df['Resistance'].ewm(span=5).mean()  # Exponential Moving Average
df['Max_Min'] = df['Resistance'].rolling(5).max() - df['Resistance'].rolling(5).min()  # Local peak-to-peak variation


In [25]:
import optuna
from xgboost import XGBClassifier

def objective(trial):
    params = {
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3),
        'n_estimators': trial.suggest_int('n_estimators', 50, 300),
        'subsample': trial.suggest_float('subsample', 0.6, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0)
    }
    model = XGBClassifier(**params, use_label_encoder=False, eval_metric='mlogloss')
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=30)


[I 2025-05-25 00:52:52,136] A new study created in memory with name: no-name-2e95b929-89fb-44fb-8bce-b842d06ec3cb
D:\SurfaceRecognitionModel\surface\Lib\site-packages\xgboost\training.py:183: UserWarning: [00:52:52] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-05-25 00:52:52,466] Trial 0 finished with value: 0.6491935483870968 and parameters: {'max_depth': 8, 'learning_rate': 0.010654900270525439, 'n_estimators': 85, 'subsample': 0.7726701198862459, 'colsample_bytree': 0.8299378603509519}. Best is trial 0 with value: 0.6491935483870968.
D:\SurfaceRecognitionModel\surface\Lib\site-packages\xgboost\training.py:183: UserWarning: [00:52:52] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
[I 2025-05-25 00:52:53,482] Trial 1 finished with value: 0.689

In [27]:
best_model = XGBClassifier(
    max_depth=10,
    learning_rate=0.06176887066197363,
    n_estimators=216,
    subsample=0.8088,
    colsample_bytree=0.8504,
    eval_metric='mlogloss'  # this one is still required
)


In [28]:
from sklearn.metrics import classification_report, confusion_matrix

print("✅ Classification Report:")
print(classification_report(y_test, y_pred, target_names=le.classes_))
print("📉 Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


✅ Classification Report:
                  precision    recall  f1-score   support

         ACRYLIC       0.55      0.70      0.62        37
 BUBBLEWRAP BACK       0.51      0.42      0.46        52
BUBBLEWRAP FRONT       0.76      0.81      0.78        69
       CARDBOARD       0.69      0.73      0.71        45
           GLASS       0.70      0.79      0.75        48
           GLOVE       0.63      0.68      0.66        38
          MARBLE       0.87      0.83      0.85        48
           METAL       0.67      0.67      0.67        52
           PAPER       0.78      0.80      0.79        54
   SMOOTH WOODEN       0.83      0.57      0.67        53

        accuracy                           0.70       496
       macro avg       0.70      0.70      0.70       496
    weighted avg       0.71      0.70      0.70       496

📉 Confusion Matrix:
[[26  2  0  2  0  3  1  0  0  3]
 [ 4 22  4  6  3  4  0  5  4  0]
 [ 1  0 56  1  0  2  3  6  0  0]
 [ 1  6  3 33  0  0  0  2  0  0]
 [ 0  2 

In [30]:
from xgboost import XGBClassifier

# Define and train best model
best_model = XGBClassifier(
    max_depth=10,
    learning_rate=0.06176887066197363,
    n_estimators=216,
    subsample=0.8088,
    colsample_bytree=0.8504,
    eval_metric='mlogloss'
)

# Fit the model (you must have X_train, y_train loaded already)
best_model.fit(X_train, y_train)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8504, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.06176887066197363,
              max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=10, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=216, n_jobs=None,
              num_parallel_tree=None, ...)

In [31]:
# One random resistance test
res_value = 8130.83
res_diff = 0
rolling_mean_5 = res_value
rolling_std_5 = 0

sample = np.array([[res_value, res_diff, rolling_mean_5, rolling_std_5]])
pred_encoded = best_model.predict(sample)[0]
pred_surface = le.inverse_transform([pred_encoded])[0]

print(f"🧠 Predicted Surface: {pred_surface}")


🧠 Predicted Surface: GLOVE


In [35]:
import pandas as pd
import numpy as np

# Load GLOVE_2
glove_test = pd.read_csv("D:/SurfaceRecognitionModel/data/GLOVE_2.csv")

# Clean and preprocess like before
glove_test = glove_test.replace("?", np.nan).dropna(axis=1, how='all')
glove_test = glove_test.select_dtypes(include=[np.number])
glove_test.columns = ['Time', 'Resistance']  # adjust if needed

# Generate features for prediction
glove_test['Resistance_diff'] = glove_test['Resistance'].diff().fillna(0)
glove_test['Rolling_mean_5'] = glove_test['Resistance'].rolling(5).mean().fillna(method='bfill')
glove_test['Rolling_std_5'] = glove_test['Resistance'].rolling(5).std().fillna(method='bfill')

X_glove = glove_test[['Resistance', 'Resistance_diff', 'Rolling_mean_5', 'Rolling_std_5']]
preds = best_model.predict(X_glove)
pred_labels = le.inverse_transform(preds)

# See how many are predicted as GLOVE
from collections import Counter
print("🧠 GLOVE_2 Predictions Summary:")
print(Counter(pred_labels))


🧠 GLOVE_2 Predictions Summary:
Counter({'GLOVE': 126, 'ACRYLIC': 6, 'BUBBLEWRAP BACK': 3, 'CARDBOARD': 2, 'GLASS': 1, 'SMOOTH WOODEN': 1})


C:\Users\ASUS\AppData\Local\Temp\ipykernel_10328\3398638715.py:8: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  glove_test = glove_test.replace("?", np.nan).dropna(axis=1, how='all')
C:\Users\ASUS\AppData\Local\Temp\ipykernel_10328\3398638715.py:14: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  glove_test['Rolling_mean_5'] = glove_test['Resistance'].rolling(5).mean().fillna(method='bfill')
C:\Users\ASUS\AppData\Local\Temp\ipykernel_10328\3398638715.py:15: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  glove_test['Rolling_std_5'] = glove_test['Resistance'].rolling(5).std().fillna(metho

In [37]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# True labels (since we know GLOVE_2 should be all 'GLOVE')
y_true = ['GLOVE'] * len(pred_labels)

# Predictions are already stored in pred_labels from earlier
y_pred = pred_labels

# Calculate metrics
acc = accuracy_score(y_true, y_pred)
print(f"✅ Accuracy on GLOVE_2: {acc:.4f} ({acc*100:.2f}%)")


✅ Accuracy on GLOVE_2: 0.9065 (90.65%)
